sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t bhaskarerumalu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bhaskarerumalu/react-test npm test

after_success:
  - docker build -t bhaskarerumalu/multi-client ./client
  - docker build -t bhaskarerumalu/multi-nginx ./nginx
  - docker build -t bhaskarerumalu/multi-server ./server
  - docker build -t bhaskarerumalu/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub

  - docker tag bhaskarerumalu/multi-client:latest mypgdocker/multi-docker:client
  - docker tag bhaskarerumalu/multi-nginx:latest mypgdocker/multi-docker:nginx
  - docker tag bhaskarerumalu/multi-server:latest mypgdocker/multi-docker:server
  - docker tag bhaskarerumalu/multi-worker:latest mypgdocker/multi-docker:worker

  - docker push mypgdocker/multi-docker:client
  - docker push mypgdocker/multi-docker:nginx
  - docker push mypgdocker/multi-docker:server
  - docker push mypgdocker/multi-docker:worker
